spring: #此项目用于演示;
  profiles:
    active:
    - dev  #此文件是Eureka整合了config模块传到git服务器端的配置文件;#用于实现config-eureka结合模块的远程依赖文件配置，而不用本地配置文件;  
---
server: #这个为Eureka-config server服务端的配置文件;
  port: 2004
  context-path: /
spring:
  profiles: dev
eureka: 
  instance:
    hostname: localhost
  client: 
    register-with-eureka: false     #false 由于该应用为注册中心，所以设置为false,代表不向注册中心注册自己。
    fetch-registry: false     #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url: 
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka注册中心交互的地址，查询服务和注册服务用到       #设置与Eureka注册中心交互的地址，查询服务和注册服务用到
---
server:
  port: 2004
  context-path: /
spring:
  profiles: test  #表示项目为测试环境项目;
eureka: 
  instance:
    hostname: localhost
  client: 
    register-with-eureka: false     #false 由于该应用为注册中心，所以设置为false,代表不向注册中心注册自己。
    fetch-registry: false     #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url: 
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka注册中心交互的地址，查询服务和注册服务用到       #设置与Eureka注册中心交互的地址，查询服务和注册服务用到